### PR TITLE
Recompile index.js and upgrade actions/core to fix all errors/warnings

### PR DESCRIPTION
**Pull request by ssrobins**
This work fixes the following issues:
https://github.com/Apple-Actions/import-codesign-certs/issues/28
https://github.com/Apple-Actions/import-codesign-certs/issues/29
https://github.com/Apple-Actions/import-codesign-certs/issues/40

To fix the runtime error in GitHub Actions, I ran the commands in the [contributing doc](https://github.com/Apple-Actions/import-codesign-certs/blob/master/CONTRIBUTING.md). Then, following the steps [in this tutorial](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action), ran the following to update index.js:
`ncc build src/main.ts --license licenses.txt`

I followed the recommendations [in this blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) to upgrade `@actions/core` to `v1.10.0`, which got rid of the runtime warning in GitHub Actions.

### CODE REVIEW

**Comment by rcdailey** [comment]
Any reason why this hasn't been merged yet?

**Comment by erikng** [comment]
I'm trying your fork/PR and the errors are gone. Looks like the certs imported properly as well.

**Comment by steveoh** [comment]
@orj are you managing these pr's or does this repo need a new maintainer?

**Comment by ssrobins** [comment]
> @orj are you managing these pr's or does this repo need a new maintainer?

@orj feel free to assign the repo to me, if you like. Grateful you set it up in the first place, but it doesn't mean you have to maintain it forever. It takes a village and all that :)

**Comment by orj** [comment]
@ssrobins Thanks for the offer. I've added you to the org.

**Comment by ssrobins** [comment]
Thanks @orj! I guess the next step would be to make a `v2` tag from latest `master` and push it, do you agree? I don't have access to do that, though.

**Comment by orj** [comment]
Ah. I'll probably have to tweak the repo permissions. I'll have to do that when I get in to work tomorrow.

**Comment by ssrobins** [comment]
@orj any updates on this?

**Comment by orj** [comment]
> @orj any updates on this?

You should have write permissions.

**Comment by ssrobins** [comment]
> > @orj any updates on this?
> 
> You should have write permissions.

Thanks, it works. `v2` tag is now pushed and `apple-actions/import-codesign-certs@v2` action now works!

**Pull request merged**
